### ISSUE TITLE
bit depth loss from 32 to 24

### ISSUE THREAD

**Issue by Armagedon13** [haganbmj/MagicSetEditor2#64]
i have a template : 
card width: 813 
card height: 1185 
card dpi: 350 
32 bit depth (i have the images to that resolution) when exporting a card maintain the aspect ratio but not the bit depth

**Comment by haganbmj** [comment]
Yeesh, I know MSE does some funky stuff when storing the card images. It crops and resizes them into the set bundle and probably throws away any of the original information... or at least doesn't use it during export.

I had originally forked to try and address some of the sizing limitations MSE had (see https://github.com/haganbmj/MagicSetEditor2/pull/3), but it sounds like there are more things to improve.

**Comment by Armagedon13** [comment]
well, i only put this issue because the resolution loss is to much, i can't test the code by myself because i can't build it.

**Comment by Armagedon13** [comment]
maybe this? 
https://github.com/haganbmj/MagicSetEditor2/blob/f97a82a837581ab48ebb9119d00c0a3e82f45fdb/src/gfx/resample_text.cpp#L33

**Comment by Armagedon13** [comment]
that's because i send the wrong one, now why make the bit depth to 24? i was thinking that read from the image or the project, maybe add the bit depth in the script of the project idk.

**Comment by Armagedon13** [comment]
https://www.computerhope.com/issues/ch001557.htm

**Comment by haganbmj** [comment]
I'm less sure that's the only place that matters now that I read more into it, it seems that wxWidgets uses a default depth based on the screen.

https://docs.wxwidgets.org/3.0/classwx_bitmap.html#a3bb19e8d368d6565f52a9c1294d80d7a

**Comment by Armagedon13** [comment]
OK, it indicates the number of pixels your screen contains, which generally today all handle 32-bit colors.

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
The change from 32bit to 24bit is due to discarding the alpha channel. This doesn't actually result in any loss of quality, just a loss of transparency. While the card render is being built, all layers have transparency and are blended correctly. It's only in the final export that transparency is omitted, which shouldn't matter.

The only problem this can cause is if you want the corners to be transparent, but you can reinstate this by writing an export script that renders the final card image with the `to_card_image` function, then adds an alpha channel with the `set_mask` function before exporting with the `write_image_file` function.

**Comment by Armagedon13** [comment]
so, nothing to discuss here, i'm closing this
