### ISSUE TITLE
Stats tab name column is too narrow.

### ISSUE THREAD

**Issue by G-e-n-e-v-e-n-s-i-S** [haganbmj/MagicSetEditor2#71]
The name column of the stats tab is too narrow:
![StatsColumn](https://github.com/haganbmj/MagicSetEditor2/assets/66968533/600c0649-71ac-4093-aa60-24f5a395eb4d)
It is just barely wide enough for English, but we started doing some localization, and for Latin languages like French, Italian and Spanish, which are less concise than English, this will not be enough. Making it adapt to the length of the longest name is probably overkill, but increasing it's width by a flat 50% or 70% is necessary.

**Comment by haganbmj** [comment]
Increasing it by a static value is easy enough, doing it dynamically based on the widest cell might be a bit tedious since it would require restructuring some of the draw logic. There seems to be a lot of dead code in that file too.

https://github.com/haganbmj/MagicSetEditor2/pull/72

This call to `getTextExtent` is probably what would need to be called as early as possible against the entire dimension list. Find the max of that then apply the width to all of the elements, unfortunately it wants to know the size ahead of time before drawing any rows right now. 

https://github.com/haganbmj/MagicSetEditor2/blob/d5f89637b984253c3358b3cdd4d279262f49ceaf/src/gui/set/stats_panel.cpp#L247
